# Implement Linear Regression with Gradient Descent

In [97]:
import numpy as np

class LinearRegression:
    def __init__(self, learning_rate=0.01, n_iters=1000):
        self.learning_rate = learning_rate
        self.n_iters = n_iters
        self.weights = None
        self.bias = None
    
    def fit(self, X, y):
        # Initialize the weights and bias to zeros
        self.weights = np.zeros((X.shape[1], 1))
        self.bias = 0
        
        # Gradient descent
        for i in range(self.n_iters):
            y_pred = self.predict(X)

            dw = (X.T.dot(y_pred - y))
            # print(dw.shape)
            db = (y_pred - y).mean()
            
            # Fill in the code to update the weights and bias
            self.weights -= self.learning_rate*dw
            self.bias -= self.learning_rate*db
            
    def predict(self, X):
        y_pred = np.dot(X, self.weights) + self.bias
        return y_pred

In [98]:
lr = LinearRegression()
# X = np.array([[1], [2], [3]])
X = np.array([[1, 2], [2, 3], [3, 4]])
y = np.array([4,5,6]).reshape(-1, 1)

lr.fit(X,y)
lr.predict(X)

array([[3.89718335],
       [4.97934228],
       [6.06150122]])

In [99]:
lr.weights

array([[-0.8232875 ],
       [ 1.90544643]])

In [100]:
X.dot(lr.weights) + lr.bias

array([[3.89718335],
       [4.97934228],
       [6.06150122]])

In [101]:
lr.bias

0.9095779772701994

In [36]:
X.shape
y.shape

(3, 1)