# Numpy

why to use numpy?

In [60]:
import numpy as np

np.array vs python lists - what differences do you know?

In [61]:
# 1-dimensonal array, or a vector
a1 = np.array([1, 2, 3], dtype=np.float32)

# 2-dimensional array, or a matrix
a2 = np.array([[1, 2, 3],
               [4, 5, 6]])

# 3-dimensional array, or a matrix (sometimes, a tensor)
a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
                [[10, 11, 12],
                 [13, 14, 15],
                 [16, 17, 18]]])

In [62]:
a1

array([1., 2., 3.], dtype=float32)

In [63]:
a1.shape, a1.ndim, a1.dtype, a1.size, type(a1)

((3,), 1, dtype('float32'), 3, numpy.ndarray)

there are different ways to create a numpy array

In [64]:
# np.array() - converting from a list
# np.ones() ; np.zeros() - creating array of a given shape 
# np.random.rand(5, 3) ; np.random.randint() - generating random numbers

In [81]:
np.random.rand(5, 3, 10)

array([[[5.50351823e-01, 6.43404560e-01, 2.77163229e-01, 8.41227772e-01,
         6.93434861e-01, 1.64766588e-01, 9.25042858e-01, 5.13978705e-01,
         9.34508177e-01, 8.31617380e-01],
        [3.90773382e-01, 3.70346830e-01, 4.34609433e-01, 9.55934959e-01,
         3.47024398e-01, 8.88921583e-01, 9.15933224e-02, 9.03266020e-01,
         6.38611708e-01, 1.20359274e-01],
        [3.08781265e-01, 4.05372718e-01, 2.43742275e-01, 6.49981951e-01,
         7.90482627e-01, 8.67881052e-01, 8.98390541e-01, 6.70492168e-01,
         3.34983153e-01, 1.90958189e-02]],

       [[3.52267124e-01, 3.81466917e-01, 7.74194061e-01, 7.01346507e-01,
         7.74646900e-01, 7.53476143e-01, 2.40957712e-02, 3.60055769e-02,
         5.29083426e-01, 3.89269192e-02],
        [5.06690694e-01, 2.54878917e-01, 4.02176491e-01, 3.74405268e-01,
         1.95209739e-01, 2.40605581e-01, 2.47366098e-01, 5.41548458e-01,
         9.06578399e-01, 1.59674259e-01],
        [5.34511471e-01, 6.14242401e-01, 1.66951078e-01, 4

In [76]:
np.array([1,2,3])

array([1, 2, 3])

In [77]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [78]:
np.zeros_like(a1)

array([0., 0., 0.], dtype=float32)

In [68]:
np.random.rand(5,3,10)*10

array([[[3.04958414, 1.86449546, 5.14774925, 4.67646878, 6.19691169,
         9.26747541, 4.1184299 , 3.31266279, 3.14194464, 3.5426441 ],
        [2.36050322, 5.35603685, 3.32526603, 6.64269973, 0.12496685,
         9.26575313, 3.94391651, 0.68272052, 1.44844691, 6.73587397],
        [7.5565795 , 2.20430568, 2.88234974, 8.38992278, 1.56537312,
         0.15753641, 6.05815105, 3.57017244, 2.87426069, 1.94261052]],

       [[7.73257326, 6.62004581, 8.67686316, 5.04387532, 1.9823912 ,
         8.3905315 , 8.61498183, 4.05691115, 4.46688548, 3.99084757],
        [0.88991991, 6.5500147 , 1.03719713, 8.09329375, 6.76443162,
         3.61856558, 0.34220036, 4.67924333, 1.43938173, 0.05222603],
        [9.61657162, 1.35439529, 6.98120198, 6.47618457, 4.63889147,
         1.3748056 , 9.70532366, 1.42913101, 0.12785103, 5.23327624]],

       [[8.24430342, 2.54125455, 9.61800553, 0.03814955, 7.66651259,
         0.45841585, 8.14193572, 2.86686699, 7.9108433 , 4.06799675],
        [8.68421722, 3.

what is np.random.seed()  ?

slicing in numpy arrays

Most mathematical functions are implemented both as methods of Numpy and as methods of Numpy object

##### Broadcasting

Broadcasting is a feature of NumPy which performs an operation across multiple dimensions of data without replicating the data

In [82]:
a1.shape, a2.shape, a3.shape

((3,), (2, 3), (2, 3, 3))

##### Reshaping

You can reshape your np.array to any possible shape (but be carefull to get what you really want)

In [84]:
a1[:,np.newaxis].shape

(3, 1)

In [85]:
a2.shape

(2, 3)

In [71]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [72]:
a2.reshape((3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [73]:
# reshaping with -1

##### sorting

np.sort() vs np.argsort()

##### Linear Algebra

all operations needed are much easier in numpy

In [88]:
a2.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [89]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [90]:
a2 @ a2.T

array([[14, 32],
       [32, 77]])

In [74]:
# this is matrix multiplication in numpy
a2.dot(a2.T) # or np.dot(a2, a2.T)

array([[14, 32],
       [32, 77]])

In [95]:
# implement matrix multiplication in pure python

def mtrx_mult(m1, m2):
    return m1 @ m2

# assert (mtrx_mult(a2, a2.T) == a2.dot(a2.T))

In [ ]:
import numpy.linalg as linalg

In [ ]:
# linalg.eigvals
# linalg.det
# linalg.inv
# linalg.solve

##### Statistics

In [ ]:
# np.mean(); np.var(); np.std()

In [ ]:
# lets calculate variance by its definition

You can generate random samples from different distributions. You can find the list here - https://numpy.org/doc/1.16/reference/routines.random.html

# Pandas

why to use pandas?

In [ ]:
import pandas as pd

##### pd.Series

In [ ]:
clubs = pd.Series(["Real", "PSG", "Liverpool"])
titles = pd.Series([35, 10, 1])

In [ ]:
clubs

In [ ]:
titles

##### pd.Dataframe

In [ ]:
club_data = pd.DataFrame({"Club name": clubs, 
                         "Titles": titles})

In [ ]:
club_data

In [ ]:
# common terms here - index, columns, rows, values (data)

In [ ]:
df = pd.read_csv('car data.csv')

##### slicing

In [ ]:
df[['Kms_Driven', 'Present_Price']].head() # .tail()

In [ ]:
df.loc[2:5]

In [ ]:
df.iloc[2:5]

In [ ]:
# df.to_csv('car_data_upd.csv')

In [ ]:
df.dtypes

In [ ]:
df.describe()

In [ ]:
df.info()

In [ ]:
df[df['Year']<2015].tail(8)

In [ ]:
df_grouped = df.groupby('Car_Name').max()
df_grouped

In [ ]:
df['Kms_Driven'].plot()

In [ ]:
df['Kms_Driven'].hist()

In [ ]:
df

##### pandas join, merge, concat and append

We will not go through the methods here. You can find all methods and examples here - https://pandas.pydata.org/docs/user_guide/merging.html

##### Dask

similar library - (e.g., for working with several dataframes parallely)
https://docs.dask.org/en/stable/

# Matplotlib

In [ ]:
from matplotlib import pyplot as plt

In [ ]:
plt.plot([1, 2, 3, 4])

In [ ]:
plt.plot([1, 2, 3, 4], [5,6,11,8])

In [ ]:
x = [1, 2, 3, 4]
y = [5, 6, 11, 8]

fig, ax = plt.subplots(figsize=(10,10))

ax.plot(x, y)
ax.set(title="Sample Simple Plot", xlabel="x-axis", ylabel="y-axis")

fig.savefig("simple-plot.png")