# Homework

In [46]:
# Please implement 2 classes below

In [47]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.utils import shuffle
import numpy as np

iris = load_iris()
X, y = iris.data, iris.target
X, y = shuffle(X, y, random_state=78)

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78, test_size=0.2)

In [48]:
from sklearn.metrics import precision_score, recall_score, accuracy_score, confusion_matrix

In [49]:
# from scipy.stats import norm

In [50]:
class NaiveBayes:
    """
    Implement Naive Bayes algorithm (multiclass case). You can find necessary formula in the screenshot
    attached.

    2.1 You need to calculate prior probabilities (P(y=yk)) as described in the picture - the proportion of
    number of data points in your train data from class k divided by number of all data points in your train
    data.
    2.2 You need to calculate conditional probabilities by using PDF of the chosen distribution.
    2.3
    Question: What does it mean to fit a gaussian naive bayes model?
    Answer: As long as we are assuming that data comes from normal distributions (different for each class),
    fit method should include finding that distributions, namely, the means and variances for each.
    So, you need to divide data into parts, where in each part the label is fixed (first part - all 0 labels,
    second part - all 1 labels etc.) and find means and variances for each feature in each part. You will use
    this values in calculating conditional probabilities by PDF.
    2.4 You can replace product of probabilities by sum of its logarithm (you know this technique from cross
    entropy loss).
    """

    def __init__(self):
        self.X = None
        self.y = None
        self.means = None
        self.std = None
        self.classes = None

    def fit(self, X, y):
        self.X = X
        self.y = y

        self.classes = np.unique(self.y)
        self.classes.sort()

        self.__find_means_and_stds()

    def prior_probability(self, y_k):
        return len([y_i for y_i in self.y if y_i == y_k]) / len(self.y)

    @staticmethod
    def pdf_normal(x, mean, std):
     var = std ** 2
     return (1 / np.sqrt(2 * var * np.pi)) * np.exp(-(((x - mean) ** 2) / (2 * var)))


    def conditional_probability(self, x, y_k):
        result = np.ndarray(X.shape[1])

        for i, feature in enumerate(x.T):
            y_k_index = nb.classes[np.where(nb.classes == y_k)]
            result[i] = self.pdf_normal(feature, self.means[i, y_k_index], self.stds[i, y_k_index])

        return np.prod(result)

    def __find_means_and_stds(self):
        self.means = np.ndarray(shape=(self.X.shape[1], len(self.classes)))
        self.stds = np.ndarray(shape=(self.X.shape[1], len(self.classes)))

        for i, y_i in enumerate(self.classes):
            self.means[:, i] = self.X[self.y == y_i].mean(axis=0)
            self.stds[:, i] = self.X[self.y == y_i].var(axis=0)

    def predict(self, X):
        y_pred = []
        for i, x in enumerate(X):
            y_pred.append(np.argmax([self.prior_probability(y_k) * self.conditional_probability(x, y_k) for y_k in self.classes]))

        y_pred = np.array(y_pred)
        return y_pred

In [51]:
nb = NaiveBayes()
nb.fit(X_train, y_train)
y_pred = nb.predict(X_test)
print(y_pred)
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))
print(recall_score(y_test, y_pred, average="micro"))
print(precision_score(y_test, y_pred, average="micro"))

[1 2 2 2 1 2 0 1 1 2 2 2 0 2 0 2 2 1 0 1 2 0 2 0 1 0 1 0 2 2]
[[ 8  0  0]
 [ 0  7  2]
 [ 0  1 12]]
0.9
0.9
0.9


In [52]:
class LinearDiscriminantAnalysis:
    def __init__(self):
        self.X = None
        self.y = None
        self.means = None
        self.cov = None
        self.classes = None

    def fit(self, X, y):
        self.X = X
        self.y = y

        self.classes = np.unique(self.y)
        self.classes.sort()

        self.__find_means()
        self.__find_cov()

    def __find_means(self):
        self.means = np.ndarray(shape=(self.X.shape[1], len(self.classes)))

        for i, y_i in enumerate(self.classes):
            self.means[:, i] = self.X[self.y == y_i].mean(axis=0)

    def prior_probability(self, y_k):
        return len([y_i for y_i in self.y if y_i == y_k]) / len(self.y)

    # todo
    def __find_cov(self):
        cov = 0
        for i, y_i in enumerate(self.classes):
            cov += np.cov(self.X[self.y == y_i].T)
            print(np.cov(self.X[self.y == y_i].T))

In [53]:
lda = LinearDiscriminantAnalysis()
lda.fit(X_train, y_train)
lda.cov
# y_pred = lda.predict(X_test)
# print(y_pred)
# print(confusion_matrix(y_test, y_pred))
# print(accuracy_score(y_test, y_pred))
# print(recall_score(y_test, y_pred, average="micro"))
# print(precision_score(y_test, y_pred, average="micro"))

[[0.12157956 0.08800232 0.01900116 0.00880372]
 [0.08800232 0.12511614 0.01261905 0.00762485]
 [0.01900116 0.01261905 0.03515099 0.00680023]
 [0.00880372 0.00762485 0.00680023 0.01124855]]
[[0.27439024 0.09322561 0.16193293 0.05239024]
 [0.09322561 0.10393902 0.08670732 0.04222561]
 [0.16193293 0.08670732 0.17119512 0.06343293]
 [0.05239024 0.04222561 0.06343293 0.03739024]]
[[0.41361862 0.1028979  0.29728228 0.05325075]
 [0.1028979  0.10303303 0.06846096 0.04812312]
 [0.29728228 0.06846096 0.2777027  0.05350601]
 [0.05325075 0.04812312 0.05350601 0.07840841]]
