# NB

In [4]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB

import numpy as np

In [5]:
class0_len = 1000
X0 = np.random.normal((0,1,2), (1,2,2), (class0_len,3))
y0 = [0]*class0_len

class1_len = 2000
X1 = np.random.normal((1,1,-1), (3,1,1), (class1_len, 3))
y1 = [1]*class1_len

In [6]:
X = np.concatenate((X0, X1))
y = y0+y1

In [7]:
X

array([[-1.55424214,  3.53066247,  0.90124965],
       [ 0.27815994,  0.4228629 ,  2.66372785],
       [ 1.465079  ,  0.49402474,  1.76752491],
       ...,
       [ 3.43677018,  3.26729159,  0.05904708],
       [-2.14781647,  1.59729414, -1.02582951],
       [-0.08090843,  0.37481197, -1.17949893]])

In [8]:
X_train, X_val, y_train, y_val = train_test_split(X, y, random_state=24)

In [9]:
gnb = GaussianNB()

In [10]:
gnb.fit(X_train, y_train)

GaussianNB()

In [11]:
gnb.score(X_train, y_train)

0.9177777777777778

In [12]:
gnb.score(X_val, y_val)

0.9146666666666666

# LDA

In [14]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
clf = LinearDiscriminantAnalysis()

In [15]:
class0_len = 1000
X0 = np.random.multivariate_normal([1,2,-1], np.array([[1, 0.9, 0.9], [0.9, 1, 0.9], [0.9, 0.9, 1]]), size=class0_len)
y0 = [0]*class0_len

class1_len = 3000
X1 = np.random.multivariate_normal([1,1,0], np.array([[1, 0.9, 0.9], [0.9, 1, 0.9], [0.9, 0.9, 1]]), size=class1_len)
y1 = [1]*class1_len

In [16]:
X = np.concatenate((X0, X1))
y = y0+y1

In [17]:
X_train, X_val, y_train, y_val = train_test_split(X, y, random_state=24)

In [18]:
gnb = GaussianNB()
gnb.fit(X_train, y_train)
gnb.score(X_val, y_val)

0.873

In [19]:
gnb.score(X_train, y_train)

0.8516666666666667

In [20]:
clf.fit(X_train, y_train)
clf.score(X_val, y_val)

0.996

In [21]:
clf.score(X_train, y_train)

0.984

In [22]:
np.cov(X0.T)

array([[0.96444761, 0.85328866, 0.86682518],
       [0.85328866, 0.96403309, 0.8620083 ],
       [0.86682518, 0.8620083 , 0.97916327]])

In [23]:
np.cov(X1.T)

array([[0.97916663, 0.8818711 , 0.87155407],
       [0.8818711 , 0.98799807, 0.87873241],
       [0.87155407, 0.87873241, 0.96702054]])

# QDA

In [24]:
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
clf = QuadraticDiscriminantAnalysis()

In [25]:
class0_len = 1000
X0 = np.random.multivariate_normal([1,2,0], np.array([[1, 0.9, 0.9], [0.9, 1, 0.9], [0.9, 0.9, 1]]), size=class0_len)
y0 = [0]*class0_len

class1_len = 3000
X1 = np.random.multivariate_normal([1,1,0], np.array([[1, 0.4, 0.2], [0.4, 1, 0.8], [0.2, 0.8, 1]]), size=class1_len)
y1 = [1]*class1_len

In [26]:
X = np.concatenate((X0, X1))
y = y0+y1

In [27]:
X_train, X_val, y_train, y_val = train_test_split(X, y, random_state=24)

In [28]:
gnb = GaussianNB()
gnb.fit(X_train, y_train)
gnb.score(X_val, y_val)

0.807

In [29]:
gnb.score(X_train, y_train)

0.777

In [30]:
clf.fit(X_train, y_train)
clf.score(X_val, y_val)

0.905

In [31]:
clf.score(X_train, y_train)

0.9056666666666666

In [32]:
clf_linear = LinearDiscriminantAnalysis()

In [33]:
clf_linear.fit(X_train, y_train)

LinearDiscriminantAnalysis()

In [34]:
clf_linear.score(X_val, y_val)

0.871

In [35]:
clf_linear.score(X_train, y_train)

0.8836666666666667